### ISSUE TITLE
Just tried Temel with Onyx (Crystal-AST-based) - looks good, thanks :-)

### ISSUE THREAD

**Issue by ozra** [f/temel#1]
https://github.com/ozra/onyx-lang/issues/60#issuecomment-201954355

**Comment by f** [comment]
Wow I just saw this, that's awesome!

**Comment by f** [comment]
I'll add this example to the readme :)

**Comment by ozra** [comment]
It's been slow during the summer, but I've just jumped back into the code the last couple of days. Hope to have the lang practically usable (for personal projects) before the end of the year. So despite the looks of the github commit-log - it's not dead :-)

Cool!

**Comment by f** [comment]
BTW, you can try `sql` (since you use `--` as comment prefix) as syntax highlighter for the Ozra lang on your README file. They look better.

**Comment by ozra** [comment]
Thanks for the tip! I've been thinking about which highlighter to abuse until github can accept Onyx!
